import { IProduct } from "@/types";

export const arrivalDatas: IProduct[] = [
  {
    _id: "1",
    image: "/oil.png",
    title: "100 Percent Apple Juice 64 fl oz Bottle",
    price: 1.09,
    category: "organic",
    isAvailable: true,
    off: 75,
  },
  {
    _id: "2",
    image: "/ar5.png",
    title: "Great Value Rising Crust Frozen Pizza, Supreme",
    price: 9.99,
    category: "cold",
    isAvailable: true,
    off: 11,
  },
  {
    _id: "3",
    image: "/ar2.png",
    title: "Simply Orange Pulp Free Juice 52 fl oz",
    price: 4.13,
    category: "premium",
    isAvailable: true,
    off: 41,
  },
  {
    _id: "4",
    image: "/ar3.png",
    title: "California Pizza Kitchen Margherita, Crispy Thin Crus…",
    price: 14.77,
    category: "cold",
    isAvailable: true,
    off: 21,
  },
  {
    _id: "5",
    image: "/ar4.png",
    title: "Cantaloupe Melon Fresh Organic Cut",
    price: 2.50,
    category: "organic",
    isAvailable: true,
    off: 50,
  },
  {
    _id: "6",
    image: "/ar5.png",
    title: "Angel Soft Toilet Paper, 9 Mega Rolls",
    price: 17.12,
    isAvailable: true,
    off: 13,
  },
];

export const arrivalDatas2: IProduct[] = [
  {
    _id: "1",
    image: "/fp1.png",
    title: "A lorem ipsum and beautifull oil bottle 100% organic",
    price: 200,
    category: "cold",
    isAvailable: true,
    off: 50,
  },
  {
    _id: "2",
    image: "/fp2.png",
    title: "A lorem ipsum and beautifull oil bottle 100% organic",
    price: 200,
    category: "cold",
    isAvailable: true,
    off: 50,
  },
  {
    _id: "3",
    image: "/fp3.png",
    title: "A lorem ipsum and beautifull oil bottle 100% organic",
    price: 200,
    category: "cold",
    isAvailable: true,
    off: 50,
  },
  {
    _id: "4",
    image: "/fp4.png",
    title: "A lorem ipsum and beautifull oil bottle 100% organic",
    price: 200,
    category: "cold",
    isAvailable: true,
    off: 50,
  },
  {
    _id: "5",
    image: "/fp5.png",
    title: "A lorem ipsum and beautifull oil bottle 100% organic",
    price: 200,
    category: "cold",
    isAvailable: true,
    off: 50,
  },
  {
    _id: "6",
    image: "/fp6.png",
    title: "A lorem ipsum and beautifull oil bottle 100% organic",
    price: 200,
    category: "cold",
    isAvailable: true,
    off: 50,
  },
];
